config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(
    :users,
    skip: [:registrations],
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  )
  root 'restaurants#index'

  devise_scope :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#new', as: :session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :diet_incompatibilities, only: %i[index new create destroy]

  resources :restaurants do
    collection do
      post :search
      get :search, to: redirect('/restaurants')
    end
  end

  resources :events do
    collection do
      post :search
      get :search, to: redirect('/events')
    end
  end

  resources :restaurant_ratings, only: :create
end

app/models/diet_incompatibility.rb
class DietIncompatibility < ApplicationRecord
  validates :restaurant_id, uniqueness: { scope: :user_id }

  belongs_to :restaurant
  belongs_to :user
end

app/controllers/diet_incompatibilities_controller.rb
class DietIncompatibilitiesController < ApplicationController
  before_action :set_diet_incompatibility, only: :destroy

  def index
    @diet_incompatibilities = DietIncompatibility
      .where(user: current_user)
      .page(params[:page])
  end

  def new
    @diet_incompatibility = DietIncompatibility.new
  end

  def create
    @diet_incompatibility = current_user.diet_incompatibilities.build(
      diet_incompatibility_params
    )

    if @diet_incompatibility.save
      flash[:success] = 'Incompatibility registered.'
      redirect_to diet_incompatibilities_path
    else
      render :new
    end
  end

  def destroy
    if @diet_incompatibility.destroy
      flash[:success] = 'Incompatibility was successfully destroyed.'
    else
      flash[:warning] = @diet_incompatibility.errors.to_sentence
    end

    redirect_to diet_incompatibilities_path
  end

  private def set_diet_incompatibility
    @diet_incompatibility = DietIncompatibility.find(params[:id])
  end

  private def diet_incompatibility_params
    params.require(:diet_incompatibility).permit(:restaurant_id)
  end
end

app/views/diet_incompatibilities/index.html.erb
<h1 class="ui dividing header">
  Your Dietary Incompatibilities
  <%= link_to new_diet_incompatibility_path, class: 'ui right floated primary button' do %>
    <i class="plus circle icon"></i> New Incompatibility
  <% end %>
</h1>

<div class="ui segment">
  <%= page_entries_info @diet_incompatibilities %>
</div>

<%= paginate @diet_incompatibilities %>

<% if @diet_incompatibilities.any? %>
  <table class="ui striped celled table">
    <thead>
      <tr>
        <th>Restaurant</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @diet_incompatibilities.each do |diet_incompatibility| %>
        <tr>
          <td><%= diet_incompatibility.restaurant %></td>
          <td>
            <%= link_to diet_incompatibility, method: :delete, class: 'ui negative button' do %>
              <i class="trash icon"></i> Delete
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @diet_incompatibilities %>
<% end %>

app/views/diet_incompatibilities/new.html.erb
<h1 class="ui header">New Event</h1>

<%= form_with(model: @diet_incompatibility, local: true, class: 'ui form') do |form| %>
  <% if @diet_incompatibility.errors.any? %>
    <div class="ui message">
      <h2 class="ui header">
        <%= pluralize(@diet_incompatibility.errors.count, 'error') %> prohibited
        this Diet Incompatibility from being saved:
      </h2>

      <ul class="list">
        <% @diet_incompatibility.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui field">
    <%= form.label :restaurant_id %>
    <%=
      form.select(
        :restaurant_id,
        options_for_select(Restaurant.order(:name).pluck(:name, :id), form.object.restaurant_id),
        { include_blank: true },
        class: 'ui fluid search dropdown'
      )
    %>
  </div>

  <div class="actions">
    <%=
      form.submit(
        class: 'ui primary button',
        data: {
          confirm: 'NOTE: Incompatibilities should only be added if there is ' \
            'very little for you to eat at this restaurant. Please ensure that ' \
            "you have read the restaurant's menu before going this route.\n\n" \
            "Examples for valid diet incompatibilities include:\n" \
            "* You are a vegan, and the restaurant only serves traditional barbecue.\n" \
            "* You do not eat gluten, and the restaurant only serves pasta.\n" \
            '* You do not eat raw fish, and the restaurant only serves sushi.'
        }
      )
    %>
  </div>
<% end %>

<br>

<%= link_to 'Back', diet_incompatibilities_path, class: 'ui button' %>