config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(
    :users,
    skip: [:registrations],
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  )
  root 'restaurants#index'

  devise_scope :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#new', as: :session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :diet_incompatibilities, only: %i[index new create destroy]

  resources :restaurants do
    collection do
      post :search
      get :search, to: redirect('/restaurants')
    end
  end

  resources :events do
    collection do
      post :search
      get :search, to: redirect('/events')
    end
  end

  resources :restaurant_ratings, only: :create
end

app/models/event.rb
class Event < ApplicationRecord
  has_paper_trail

  validates :name, presence: true
  validates :occurs_on, presence: true, uniqueness: true

  belongs_to :restaurant, optional: true

  def self.next
    where(arel_table[:occurs_on].gt(Time.zone.today))
      .order(occurs_on: :asc)
      .first
  end

  def to_s
    name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :ensure_admin, only: :destroy
  before_action :set_event, only: %i[show edit update destroy]

  def search
    index
    render :index
  end

  def index
    params[:q] ||= { s: 'occurs_on desc' }
    @search = Event.ransack(params[:q])
    @events = @search.result.page(params[:page])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, success: 'Event was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, success: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_url, success: 'Event was successfully destroyed.'
    else
      redirect_to events_url, warning: @event.errors.to_sentence
    end
  end

  private def set_event
    @event = Event.find(params[:id])
  end

  private def event_params
    params.require(:event).permit(:name, :restaurant_id, :occurs_on)
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, class: 'ui form') do |form| %>
  <% if event.errors.any? %>
    <div class="ui message">
      <h2 class="ui header">
        <%= pluralize(event.errors.count, 'error') %> prohibited this
        event from being saved:
      </h2>

      <ul class="list">
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'ui labeled input' %>
  </div>

  <div class="ui field">
    <%= form.label :occurs_on %>

    <div class="ui date calendar">
      <div class="ui input left icon">
        <i class="calendar icon"></i>
        <%= form.text_field :occurs_on %>
      </div>
    </div>
  </div>

  <div class="ui field">
    <%= form.label :restaurant_id %>
    <%=
      form.select(
        :restaurant_id,
        options_for_select(Restaurant.order(:name).pluck(:name, :id), form.object.restaurant_id),
        { include_blank: true },
        class: 'ui fluid search dropdown'
      )
    %>
  </div>

  <div class="actions">
    <%= form.submit class: 'ui primary button' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="ui header">Editing Event</h1>

<%= render 'form', event: @event %>

<br>

<%= link_to 'Back', events_path, class: 'ui button' %>

app/views/events/index.html.erb
<h1 class="ui dividing header">
  Events
  <%= link_to new_event_path, class: 'ui right floated primary button' do %>
    <i class="plus circle icon"></i> New Event
  <% end %>
</h1>

<%= search_form_for @search, method: :post, url: search_events_path, html: { class: 'ui form' } do |f| %>
  <div class="two fields">
    <div class="field">
      <%= f.label :name_cont, 'Name' %>
      <%= f.text_field :name_cont %>
    </div>

    <div class="field">
      <%= f.label :restaurant_id_eq, 'Restaurant' %>
      <%=
        f.select(
          :restaurant_id_eq,
          options_for_select(
            Restaurant.order(:name).pluck(:name, :id),
            f.object.restaurant_id_eq
          ),
          { include_blank: true },
          class: 'ui fluid search dropdown'
        )
      %>
    </div>

    <div class="field">
      <%= f.label :occurs_on_gteq, 'Min Date' %>

      <div class="ui date calendar">
        <div class="ui input left icon">
          <i class="calendar icon"></i>
          <%= f.text_field :occurs_on_gteq %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :occurs_on_lteq, 'Max Date' %>

      <div class="ui date calendar">
        <div class="ui input left icon">
          <i class="calendar icon"></i>
          <%= f.text_field :occurs_on_lteq %>
        </div>
      </div>
    </div>
  </div>

  <br>

  <%= f.submit class: 'ui primary button', data: { disable_with: 'Searching...' } %>
<% end %>

<div class="ui segment">
  <%= page_entries_info @events %>
</div>

<%= paginate @events %>

<table class="ui striped celled table">
  <thead>
    <tr>
      <th><%= sort_link @search, 'name', { action: :search }, method: :post %></th>
      <th>
        <%= sort_link @search, 'occurs_on', 'Date', { action: :search }, method: :post %>
      </th>
      <th>Restaurant</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.occurs_on %></td>
        <td><%= link_to(event.restaurant, event.restaurant) if event.restaurant %></td>
        <td>
          <%= link_to event, class: 'ui secondary button' do %>
            <i class="eye icon"></i> Show
          <% end %>
          <%= link_to edit_event_path(event), class: 'ui secondary button' do %>
            <i class="pencil icon"></i> Edit
          <% end %>

          <% if current_user.admin? %>
            <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui negative button' do %>
              <i class="trash icon"></i> Delete
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @events %>

app/views/events/new.html.erb
<h1 class="ui header">New Event</h1>

<%= render 'form', event: @event %>

<br>

<%= link_to 'Back', events_path, class: 'ui button' %>

app/views/events/show.html.erb
<h1 class="ui dividing header">
  <%= @event.name %>
  <%=
    link_to(
      content_tag(:i, '', class: 'undo icon') + ' Back',
      events_path,
      class: 'ui right floated button'
    )
  %>
  <%=
    link_to(
      content_tag(:i, '', class: 'pencil alternate icon') + ' Edit',
      edit_event_path(@event),
      class: 'ui right floated primary button'
    )
  %>
</h1>

<div class="ui large middle aligned list">
  <div class="item">
    <strong>Restaurant:</strong>
    <%= link_to @event.restaurant %>
  </div>

  <div class="item">
    <strong>Date:</strong>
    <%= @event.occurs_on %>
  </div>
</div>

<br>

<%= link_to 'Back', events_path, class: 'ui button' %>