config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(
    :users,
    skip: [:registrations],
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  )
  root 'restaurants#index'

  devise_scope :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#new', as: :session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :diet_incompatibilities, only: %i[index new create destroy]

  resources :restaurants do
    collection do
      post :search
      get :search, to: redirect('/restaurants')
    end
  end

  resources :events do
    collection do
      post :search
      get :search, to: redirect('/events')
    end
  end

  resources :restaurant_ratings, only: :create
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_paper_trail

  validates :food_type, presence: true
  validates :delivery_method, presence: true
  validates :menu_url, presence: true
  validates :menu_url, uri: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :events, dependent: :destroy
  has_many :diet_incompatibilities, dependent: :destroy
  has_many :restaurant_ratings, dependent: :destroy
  # View; no dependent option needed
  has_many :user_ratings

  scope :recent_picks, -> do
    joins(:events)
      .order(occurs_on: :desc)
      .where(
        Event.arel_table[:occurs_on].lt(Time.zone.today).and(
          Event.arel_table[:occurs_on].gt(1.month.ago)
        )
      )
  end

  def to_s
    name
  end

  def rating_for(user)
    restaurant_ratings.find { |rating| rating.user_id == user.id }
  end

  def average_rating
    user_ratings.average(:rating)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :ensure_admin, only: :destroy
  before_action :set_restaurant, only: %i[show edit update destroy]

  def search
    index
    render :index
  end

  def index
    params[:q] ||= { s: 'name' }
    @search = Restaurant.includes(:restaurant_ratings).ransack(params[:q])
    @restaurants = @search.result.page(params[:page])
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, success: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, success: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @restaurant.destroy
      redirect_to restaurants_url,
                  success: 'Restaurant was successfully destroyed.'
    else
      redirect_to restaurants_url, warning: @restaurant.errors.to_sentence
    end
  end

  private def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  private def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :menu_url,
      :food_type,
      :delivery_method
    )
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true, class: 'ui form') do |form| %>
  <% if restaurant.errors.any? %>
    <div class="ui message">
      <h2 class="ui header">
        <%= pluralize(restaurant.errors.count, 'error') %> prohibited this
        restaurant from being saved:
      </h2>

      <ul class="list">
        <% restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'ui corner labeled input' %>
  </div>

  <div class="ui field">
    <%= form.label :menu_url %>
    <%= form.text_field :menu_url, class: 'ui corner labeled input' %>
  </div>

  <div class="ui field">
    <%= form.label :delivery_method %>
    <%=
      form.select(
        :delivery_method,
        ['GrubHub', 'DoorDash', 'Takeout Central', 'Provided by restaurant', 'Pickup'],
        { include_blank: true },
        class: 'ui fluid search dropdown'
      )
    %>
  </div>

  <div class="ui field">
    <%= form.label :food_type %>
    <%=
      form.select(
        :food_type,
        options_for_select(Restaurant.all.pluck(:food_type).uniq, form.object.food_type),
        { include_blank: true },
        class: 'ui fluid search dropdown',
        data: { allow_additions: true }
      )
    %>
  </div>

  <div class="actions">
    <%= form.submit class: 'ui primary button' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1 class="ui header">Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<br>

<%= link_to 'Back', restaurants_path, class: 'ui button' %>

app/views/restaurants/index.html.erb
<h1 class="ui dividing header">
  Restaurants
  <%= link_to new_restaurant_path, class: 'ui right floated primary button' do %>
    <i class="plus circle icon"></i> New Restaurant
  <% end %>
</h1>

<%= search_form_for @search, method: :post, url: search_restaurants_path, html: { class: 'ui form' } do |f| %>
  <div class="three fields">
    <div class="field">
      <%= f.label :name_cont, 'Name' %>
      <%= f.text_field :name_cont %>
    </div>

    <div class="field">
      <%= f.label :food_type_eq, 'Food Type' %>
      <%=
        f.select(
          :food_type_eq,
          options_for_select(
            Restaurant.all.pluck(:food_type).uniq,
            f.object.food_type_eq
          ),
          { include_blank: true },
          class: 'ui fluid search dropdown'
        )
      %>
    </div>

    <div class="field">
      <%= f.label :delivery_method_eq, 'Delivery Method' %>
      <%=
        f.select(
          :delivery_method_eq,
          ['GrubHub', 'DoorDash', 'Takeout Central', 'Provided by restaurant', 'Pickup'],
          { include_blank: true },
          class: 'ui fluid search dropdown'
        )
      %>
    </div>
  </div>

  <br>

  <%= f.submit class: 'ui primary button', data: { disable_with: 'Searching...' } %>
<% end %>

<div class="ui segment">
  <%= page_entries_info @restaurants %>
</div>

<%= paginate @restaurants %>

<table class="ui striped celled table">
  <thead>
    <tr>
      <th><%= sort_link @search, 'name', { action: :search }, method: :post %></th>
      <th><%= sort_link @search, 'food_type', { action: :search }, method: :post %></th>
      <th>Menu</th>
      <th>Your Rating</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.food_type %></td>
        <td><%= link_to 'Menu', restaurant.menu_url %></td>
        <td>
          <%=
            content_tag(
              :div,
              '',
              class: 'ui large blue rating',
              data: {
                url: restaurant_ratings_path(restaurant_id: restaurant.id),
                rating: restaurant.rating_for(current_user).try(:stars)
              }
            )
          %>
        </td>
        <td>
          <%= link_to restaurant, class: 'ui secondary button' do %>
            <i class="eye icon"></i> Show
          <% end %>
          <%= link_to edit_restaurant_path(restaurant), class: 'ui secondary button' do %>
            <i class="pencil icon"></i> Edit
          <% end %>

          <% if current_user.admin? %>
            <%= link_to restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui negative button' do %>
              <i class="trash icon"></i> Delete
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @restaurants %>

app/views/restaurants/new.html.erb
<h1 class="ui header">New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<br>

<%= link_to 'Back', restaurants_path, class: 'ui button' %>

app/views/restaurants/show.html.erb
<h1 class="ui dividing header">
  <%= @restaurant.name %>
  <%=
    link_to(
      content_tag(:i, '', class: 'undo icon') + ' Back',
      restaurants_path,
      class: 'ui right floated button'
    )
  %>
  <%=
    link_to(
      content_tag(:i, '', class: 'pencil alternate icon') + ' Edit',
      edit_restaurant_path(@restaurant),
      class: 'ui right floated primary button'
    )
  %>
</h1>

<div class="ui large middle aligned list">
  <div class="item">
    <strong>Menu:</strong>
    <%= link_to 'Menu', @restaurant.menu_url %>
  </div>

  <div class="item">
    <strong>Food Type:</strong>
    <%= @restaurant.food_type %>
  </div>
</div>

<h3 class="ui header">Chosen for Events:</h2>

<table class="ui striped celled table">
  <thead>
    <tr>
      <th>Event</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant.events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.occurs_on %></td>
        <td><%= link_to 'Show', event, class: 'ui secondary button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', restaurants_path, class: 'ui button' %>